import { CalendarDays, Laptop, MapPin } from "lucide-react";

/** 年間行事 */
export const ANNUAL_EVENTS = [
  {
    month: "4月",
    season: "1st Semester",
    title: "新歓イベント",
    desc: "新入生を歓迎し、Digitartの活動内容を紹介する最初のイベント。ゲーム大会や交流会を通じて、同級生や先輩メンバーと仲良くなれる機会です。",
    image: "/images/events/welcome-event.jpg",
    tagColor: "bg-green-100 text-green-700",
    url: null,
  },
  {
    month: "4-5月",
    season: "1st Semester",
    title: "新入生向け講座",
    desc: "プログラミングやチーム開発の基礎を学ぶ新入生向けの集中講座。数週間にわたり、実際に手を動かしながら学べる内容で、初心者が安心して参加できるようサポート体制も充実させています。",
    image: "/images/events/welcome-lecture.jpg",
    tagColor: "bg-green-100 text-green-700",
    url: null,
  },
  {
    month: "6月",
    season: "1st Semester",
    title: "BBQ",
    desc: "新入生歓迎と親睦を兼ねたBBQイベント。メンバー同士の交流を深める絶好の機会となっています。食事を楽しみながら、サークル活動や趣味の話で盛り上がります。",
    image: "/images/events/bbq.jpg",
    tagColor: "bg-green-100 text-green-700",
    url: null,
  },
  {
    month: "6-7月",
    season: "1st Semester",
    title: "わかば創作会",
    desc: "学習会で得たスキルを活かして、実際に作品を作ることに挑戦するイベント。チームで協力して作品を制作します。完成した作品は学園祭やオンラインで発表します。",
    image: "/images/events/wakaba-create.jpg",
    color: "from-green-300 to-lime-300",
    tagColor: "bg-green-100 text-green-700",
    url: null,
  },
  {
    month: "8-9月",
    season: "Summer Vacation",
    title: "夏季輪講",
    desc: "メンバーが持ち寄りで趣味や専門知識を紹介する輪講イベント。テーマはAI、Web開発、ゲームなど多岐にわたり、オンラインで開催されるため家から気軽に参加できます。",
    image: "/images/events/summer-lecture.jpg",
    tagColor: "bg-sky-100 text-sky-700",
    url: null,
  },
  {
    month: "9月",
    season: "Summer Vacation",
    title: "夏合宿",
    desc: "サークル最大のイベントの一つ。数日間の合宿を通じて、メンバー同士の親睦を深めます。過去には伊豆半島で開催し、リフレッシュしながら交流を行いました。",
    image: "/images/events/summer-camp.jpg",
    tagColor: "bg-sky-100 text-sky-700",
    url: null,
  },
  {
    month: "10月",
    season: "2nd Semester",
    title: "学園祭出展(相模原祭)",
    desc: "大学の学園祭「相模原祭」での展示イベント。メンバーが制作した作品を展示し、来場者に体験してもらいます。過去にはVRゲームやオリジナルゲームなどを出展し、好評を博しました。",
    image: "/images/events/sagamihara-fes.jpg",
    tagColor: "bg-amber-100 text-amber-700",
    url: null,
  },
  {
    month: "11月",
    season: "2nd Semester",
    title: "学園祭出展(青山祭)",
    desc: "大学の学園祭「青山祭」での展示イベント。相模原祭で展示した作品をさらにブラッシュアップして出展することが多いです。来場者からのフィードバックを得る貴重な機会となっています。",
    image: "/images/events/aoyama-fes.jpg",
    tagColor: "bg-amber-100 text-amber-700",
    url: null,
  },
  {
    month: "11-12月",
    season: "2nd Semester",
    title: "ハッカソン",
    desc: "テーマを決めて、1ヶ月で作品を作るハッカソンイベント。個人参加もチーム参加も歓迎。過去には「circle」をテーマにしたハッカソンを開催し、斬新なアイデアが多数生まれました。",
    image: "/images/events/hackathon.jpg",
    tagColor: "bg-amber-100 text-amber-700",
    url: null,
  },
  {
    month: "1月",
    season: "2nd Semester",
    title: "LT会",
    desc: "ライトニングトーク形式で、メンバーが自由なテーマで5分間のプレゼンを行う年末恒例イベント。技術ネタからポエム、趣味の話まで何でもOK。",
    image: "/images/events/lt.jpg",
    tagColor: "bg-amber-100 text-amber-700",
    url: null,
  },
  {
    month: "2月",
    season: "Spring Vacation",
    title: "追い出し会",
    desc: "年度末の総まとめ。1年間の活動成果を振り返り、卒業するメンバーを送り出す感謝のイベント。",
    image: "/images/events/graduation.jpg",
    tagColor: "bg-pink-100 text-pink-700",
    url: null,
  },
];

/** 定例活動 */
export const REGULAR_ACTIVITIES = [
  {
    label: "対面活動",
    detail: "毎週月曜･木曜 18:45-21:00",
    icon: CalendarDays,
  },
  {
    label: "活動場所",
    detail: "相模原キャンパスF棟 + オンライン",
    icon: MapPin,
  },
  {
    label: "オンライン(Discord)",
    detail: "24時間いつでも活動中！",
    icon: Laptop,
  },
];
